#!/usr/bin/env python
import sys

# Read input line by line from stdin
for line in sys.stdin:
    # Remove leading and trailing whitespaces, and split by any whitespace
    words = line.strip().split()
    
    # For each word in the line, print the word and a count of 1
    for word in words:
        print(f"{word}\t1")
